basePath: /email/v1
definitions:
  model.Empty:
    type: object
  model.MailData:
    properties:
      createdAt:
        description: 邮件创建时间 到秒
        type: integer
      emailId:
        description: 邮件ID
        type: integer
      emailType:
        description: 邮件类型：1 福利发放；2 系统通知
        type: integer
      isReward:
        description: 是否有奖励：1 是；2 否
        type: integer
      itemList:
        description: 奖励物品 是 itemId
        items:
          $ref: '#/definitions/model.MailItem'
        type: array
      remark:
        description: 描述
        type: string
      status:
        description: 邮件状态 1.未读 2.已读 3.已领取
        type: integer
      title:
        description: 邮件标题
        type: string
    type: object
  model.MailItem:
    properties:
      count:
        description: 物品的数量
        type: string
      id:
        description: 物品ID
        type: integer
    type: object
  model.SetMailDataReq:
    properties:
      emailId:
        description: 其中EmailId = 0则把所有邮件标记成已读
        type: integer
    type: object
  model.TakeItemResp:
    properties:
      itemList:
        description: 奖励物品 是 itemId
        items:
          $ref: '#/definitions/model.MailItem'
        type: array
    type: object
  model.UserMailListResp:
    properties:
      list:
        description: 邮件列表
        items:
          $ref: '#/definitions/model.MailData'
        type: array
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: email 服务接口
  title: email 服务接口
  version: "1.0"
paths:
  /del-email:
    post:
      description: Email
      parameters:
      - description: dev.kxmj.com
        in: header
        name: BundleId
        required: true
        type: string
      - description: 0033-0000-9999-9999-9999-1111
        in: header
        name: DeviceId
        required: true
        type: string
      - description: 9cb9aaf4e28d5094fbca383255ecbafbbabb95c40c758843054480391f448ee8
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SetMailDataReq'
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.TakeItemResp'
              type: object
      summary: 用户删除邮件
      tags:
      - Email
  /email-list:
    get:
      description: Email
      parameters:
      - description: dev.kxmj.com
        in: header
        name: BundleId
        required: true
        type: string
      - description: 0033-0000-9999-9999-9999-1111
        in: header
        name: DeviceId
        required: true
        type: string
      - description: 9cb9aaf4e28d5094fbca383255ecbafbbabb95c40c758843054480391f448ee8
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.UserMailListResp'
              type: object
      summary: 获取用户邮件列表
      tags:
      - Email
  /set-email-read:
    post:
      description: Email
      parameters:
      - description: dev.kxmj.com
        in: header
        name: BundleId
        required: true
        type: string
      - description: 0033-0000-9999-9999-9999-1111
        in: header
        name: DeviceId
        required: true
        type: string
      - description: 9cb9aaf4e28d5094fbca383255ecbafbbabb95c40c758843054480391f448ee8
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SetMailDataReq'
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Empty'
              type: object
      summary: 设置用户邮件为已读
      tags:
      - Email
  /take-email-item:
    post:
      description: Email
      parameters:
      - description: dev.kxmj.com
        in: header
        name: BundleId
        required: true
        type: string
      - description: 0033-0000-9999-9999-9999-1111
        in: header
        name: DeviceId
        required: true
        type: string
      - description: 9cb9aaf4e28d5094fbca383255ecbafbbabb95c40c758843054480391f448ee8
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SetMailDataReq'
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.TakeItemResp'
              type: object
      summary: 领取邮件里面的物品
      tags:
      - Email
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
