// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.3.0
// source: lobby.proto

package lobby_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MID int32

const (
	MID_INVALID          MID = 0   // 无效消息
	MID_PAUSE_GAME       MID = 801 // 暂停游戏
	MID_CONTINUE_GAME    MID = 802 // 继续游戏
	MID_REGISTER         MID = 899 // 服务注册
	MID_UNREGISTER       MID = 900 // 取消注册
	MID_ON_LINE          MID = 901 // 用户上线 Online
	MID_OFF_LINE         MID = 902 // 用户下线 Offline
	MID_ENTER_DESK       MID = 903 // 进入桌子 EnterDesk
	MID_LEAVE_DESK       MID = 904 // 离开桌子 LeaveDesk
	MID_RISE_BUY_SUCCESS MID = 905 // 复活卡购买成功 RiseBuySuccess
)

// Enum value maps for MID.
var (
	MID_name = map[int32]string{
		0:   "INVALID",
		801: "PAUSE_GAME",
		802: "CONTINUE_GAME",
		899: "REGISTER",
		900: "UNREGISTER",
		901: "ON_LINE",
		902: "OFF_LINE",
		903: "ENTER_DESK",
		904: "LEAVE_DESK",
		905: "RISE_BUY_SUCCESS",
	}
	MID_value = map[string]int32{
		"INVALID":          0,
		"PAUSE_GAME":       801,
		"CONTINUE_GAME":    802,
		"REGISTER":         899,
		"UNREGISTER":       900,
		"ON_LINE":          901,
		"OFF_LINE":         902,
		"ENTER_DESK":       903,
		"LEAVE_DESK":       904,
		"RISE_BUY_SUCCESS": 905,
	}
)

func (x MID) Enum() *MID {
	p := new(MID)
	*p = x
	return p
}

func (x MID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[0].Descriptor()
}

func (MID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[0]
}

func (x MID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MID.Descriptor instead.
func (MID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

type PauseGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
}

func (x *PauseGame) Reset() {
	*x = PauseGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseGame) ProtoMessage() {}

func (x *PauseGame) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseGame.ProtoReflect.Descriptor instead.
func (*PauseGame) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *PauseGame) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ContinueGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
}

func (x *ContinueGame) Reset() {
	*x = ContinueGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContinueGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueGame) ProtoMessage() {}

func (x *ContinueGame) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueGame.ProtoReflect.Descriptor instead.
func (*ContinueGame) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *ContinueGame) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 服务注册
type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SvrType uint32 `protobuf:"varint,1,opt,name=svr_type,json=svrType,proto3" json:"svr_type,omitempty"` // 服务类型
	SvrId   uint32 `protobuf:"varint,2,opt,name=svr_id,json=svrId,proto3" json:"svr_id,omitempty"`       // 服务Id
	Addr    string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`                       // 服务监听IP
	Port    uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                      // 服务监听端口
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetSvrType() uint32 {
	if x != nil {
		return x.SvrType
	}
	return 0
}

func (x *Register) GetSvrId() uint32 {
	if x != nil {
		return x.SvrId
	}
	return 0
}

func (x *Register) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Register) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// 取消注册
type UnRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SvrType uint32 `protobuf:"varint,1,opt,name=svr_type,json=svrType,proto3" json:"svr_type,omitempty"` // 服务类型
	SvrId   uint32 `protobuf:"varint,2,opt,name=svr_id,json=svrId,proto3" json:"svr_id,omitempty"`       // 服务Id
}

func (x *UnRegister) Reset() {
	*x = UnRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegister) ProtoMessage() {}

func (x *UnRegister) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegister.ProtoReflect.Descriptor instead.
func (*UnRegister) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *UnRegister) GetSvrType() uint32 {
	if x != nil {
		return x.SvrType
	}
	return 0
}

func (x *UnRegister) GetSvrId() uint32 {
	if x != nil {
		return x.SvrId
	}
	return 0
}

// 用户上线
type Online struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 玩家ID
	SvrType uint32 `protobuf:"varint,2,opt,name=svr_type,json=svrType,proto3" json:"svr_type,omitempty"` // 服务类型
	SvrId   uint32 `protobuf:"varint,3,opt,name=svr_id,json=svrId,proto3" json:"svr_id,omitempty"`       // 服务Id
}

func (x *Online) Reset() {
	*x = Online{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Online) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Online) ProtoMessage() {}

func (x *Online) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Online.ProtoReflect.Descriptor instead.
func (*Online) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *Online) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Online) GetSvrType() uint32 {
	if x != nil {
		return x.SvrType
	}
	return 0
}

func (x *Online) GetSvrId() uint32 {
	if x != nil {
		return x.SvrId
	}
	return 0
}

// 用户下线
type Offline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 玩家ID
	SvrType uint32 `protobuf:"varint,2,opt,name=svr_type,json=svrType,proto3" json:"svr_type,omitempty"` // 服务类型
	SvrId   uint32 `protobuf:"varint,3,opt,name=svr_id,json=svrId,proto3" json:"svr_id,omitempty"`       // 服务Id
}

func (x *Offline) Reset() {
	*x = Offline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *Offline) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Offline) GetSvrType() uint32 {
	if x != nil {
		return x.SvrType
	}
	return 0
}

func (x *Offline) GetSvrId() uint32 {
	if x != nil {
		return x.SvrId
	}
	return 0
}

// 进入桌子
type EnterDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 玩家ID
	SvrType uint32 `protobuf:"varint,2,opt,name=svr_type,json=svrType,proto3" json:"svr_type,omitempty"` // 游戏类型
	SvrId   uint32 `protobuf:"varint,3,opt,name=svr_id,json=svrId,proto3" json:"svr_id,omitempty"`       // 服务ID
	RoomId  uint32 `protobuf:"varint,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`    // 房间号
	DeskId  uint32 `protobuf:"varint,5,opt,name=desk_id,json=deskId,proto3" json:"desk_id,omitempty"`    // 桌号
}

func (x *EnterDesk) Reset() {
	*x = EnterDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterDesk) ProtoMessage() {}

func (x *EnterDesk) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterDesk.ProtoReflect.Descriptor instead.
func (*EnterDesk) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *EnterDesk) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnterDesk) GetSvrType() uint32 {
	if x != nil {
		return x.SvrType
	}
	return 0
}

func (x *EnterDesk) GetSvrId() uint32 {
	if x != nil {
		return x.SvrId
	}
	return 0
}

func (x *EnterDesk) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *EnterDesk) GetDeskId() uint32 {
	if x != nil {
		return x.DeskId
	}
	return 0
}

// 离开桌子
type LeaveDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 玩家ID
	SvrType uint32 `protobuf:"varint,2,opt,name=svr_type,json=svrType,proto3" json:"svr_type,omitempty"` // 游戏类型
	SvrId   uint32 `protobuf:"varint,3,opt,name=svr_id,json=svrId,proto3" json:"svr_id,omitempty"`       // 服务ID
	RoomId  uint32 `protobuf:"varint,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`    // 房间号
	DeskId  uint32 `protobuf:"varint,5,opt,name=desk_id,json=deskId,proto3" json:"desk_id,omitempty"`    // 桌号
}

func (x *LeaveDesk) Reset() {
	*x = LeaveDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveDesk) ProtoMessage() {}

func (x *LeaveDesk) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveDesk.ProtoReflect.Descriptor instead.
func (*LeaveDesk) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveDesk) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaveDesk) GetSvrType() uint32 {
	if x != nil {
		return x.SvrType
	}
	return 0
}

func (x *LeaveDesk) GetSvrId() uint32 {
	if x != nil {
		return x.SvrId
	}
	return 0
}

func (x *LeaveDesk) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LeaveDesk) GetDeskId() uint32 {
	if x != nil {
		return x.DeskId
	}
	return 0
}

// 复活卡购买成功
type RiseBuySuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RiseBuySuccess) Reset() {
	*x = RiseBuySuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiseBuySuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiseBuySuccess) ProtoMessage() {}

func (x *RiseBuySuccess) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiseBuySuccess.ProtoReflect.Descriptor instead.
func (*RiseBuySuccess) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8}
}

var File_lobby_proto protoreflect.FileDescriptor

var file_lobby_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x22, 0x24, 0x0a, 0x09, 0x50, 0x61, 0x75, 0x73, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x73, 0x76, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x76,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x76, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3e, 0x0a, 0x0a, 0x55, 0x6e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x76, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x76, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x73, 0x76, 0x72, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x06, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x76, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x73, 0x76, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x76, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x76, 0x72, 0x49, 0x64, 0x22, 0x54,
	0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x76, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x76, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x76, 0x72, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x65,
	0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x76, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x76, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x76, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x76, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x88, 0x01, 0x0a, 0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x76, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x76, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x76, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x69,
	0x73, 0x65, 0x42, 0x75, 0x79, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0xad, 0x01, 0x0a,
	0x03, 0x4d, 0x49, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0a, 0x50, 0x41, 0x55, 0x53, 0x45, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x10,
	0xa1, 0x06, 0x12, 0x12, 0x0a, 0x0d, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x10, 0xa2, 0x06, 0x12, 0x0d, 0x0a, 0x08, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x45, 0x52, 0x10, 0x83, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x55, 0x4e, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x45, 0x52, 0x10, 0x84, 0x07, 0x12, 0x0c, 0x0a, 0x07, 0x4f, 0x4e, 0x5f, 0x4c, 0x49, 0x4e,
	0x45, 0x10, 0x85, 0x07, 0x12, 0x0d, 0x0a, 0x08, 0x4f, 0x46, 0x46, 0x5f, 0x4c, 0x49, 0x4e, 0x45,
	0x10, 0x86, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x53,
	0x4b, 0x10, 0x87, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x44, 0x45,
	0x53, 0x4b, 0x10, 0x88, 0x07, 0x12, 0x15, 0x0a, 0x10, 0x52, 0x49, 0x53, 0x45, 0x5f, 0x42, 0x55,
	0x59, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x89, 0x07, 0x42, 0x0b, 0x5a, 0x09,
	0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData = file_lobby_proto_rawDesc
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_proto_rawDescData)
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lobby_proto_goTypes = []interface{}{
	(MID)(0),               // 0: lobby.MID
	(*PauseGame)(nil),      // 1: lobby.PauseGame
	(*ContinueGame)(nil),   // 2: lobby.ContinueGame
	(*Register)(nil),       // 3: lobby.Register
	(*UnRegister)(nil),     // 4: lobby.UnRegister
	(*Online)(nil),         // 5: lobby.Online
	(*Offline)(nil),        // 6: lobby.Offline
	(*EnterDesk)(nil),      // 7: lobby.EnterDesk
	(*LeaveDesk)(nil),      // 8: lobby.LeaveDesk
	(*RiseBuySuccess)(nil), // 9: lobby.RiseBuySuccess
}
var file_lobby_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContinueGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Online); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiseBuySuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		EnumInfos:         file_lobby_proto_enumTypes,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_rawDesc = nil
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
